runtime: php82
instance_class: F1
document_root: public

env_variables:
  APP_NAME: Laravel
  APP_ENV: production
  APP_KEY: base64:LY/CW6YNQBHnsnRlHuNduaoWWKiiNmKqN3nkvqi9qQU=
  APP_DEBUG: false
  APP_URL: https://textyapp-83044375023.europe-west1.run.app
  APP_LOCALE: en
  APP_FALLBACK_LOCALE: en
  APP_FAKER_LOCALE: en_US
  APP_MAINTENANCE_DRIVER: file
  PHP_CLI_SERVER_WORKERS: 4
  BCRYPT_ROUNDS: 12
  LOG_CHANNEL: stack
  LOG_STACK: single
  LOG_DEPRECATIONS_CHANNEL: null
  LOG_LEVEL: debug
  DB_CONNECTION: mysql
  DB_HOST: "/cloudsql/your-project-id:europe-west1:your-instance"
  DB_PORT: 3306
  DB_DATABASE: instagram
  DB_USERNAME: root
  DB_PASSWORD: ""
  SESSION_DRIVER: database
  SESSION_LIFETIME: 120
  SESSION_ENCRYPT: false
  SESSION_PATH: /
  SESSION_DOMAIN: null
  BROADCAST_CONNECTION: log
  FILESYSTEM_DISK: local
  QUEUE_CONNECTION: database
  CACHE_STORE: database
  REDIS_CLIENT: phpredis
  REDIS_HOST: "your-redis-host"
  REDIS_PASSWORD: null
  REDIS_PORT: 6379
  MAIL_MAILER: log
  MAIL_SCHEME: null
  MAIL_HOST: 127.0.0.1
  MAIL_PORT: 2525
  MAIL_USERNAME: null
  MAIL_PASSWORD: null
  MAIL_FROM_ADDRESS: "hello@example.com"
  MAIL_FROM_NAME: "${APP_NAME}"
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_DEFAULT_REGION: us-east-1
  AWS_BUCKET: ""
  AWS_USE_PATH_STYLE_ENDPOINT: false
  VITE_APP_NAME: "${APP_NAME}"

handlers:
  - url: /.*
    script: auto

build:
  - composer install --no-dev --optimize-autoloader
  - npm install && npm run build